development:
  adapter: redis
  url: redis://localhost:6379

# development:
#   adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_TO_GO_URL"] %>
  channel_prefix: juice-box_production
